base_dir_fd = '...' # Directory that contains detections by fine level detector
base_dir_cd = '...' # Directory that contains detections by coarse level detector
base_dir_gt = '...' # Directory that contains ground truth bounding boxes
base_dir_reward_fd = '...' # Directory that contains AP or AR values by the fine detector
base_dir_reward_cd = '...' # Directory that contains AP or AR values by the coarse detector
num_actions = 9 # Hyperparameter, should be equal to num_windows * num_windows
num_windows = 3 # Number of windows in one dimension
img_size_fd = 320 # Image size used to train the fine level detector
img_size_cd = 64 # Image size used to train the coarse level detector
